FROM ruby:3.4.7-slim

# Install development packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libyaml-dev \
    postgresql-client \
    curl \
    vim && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

# Install Yarn
RUN npm install -g yarn

CMD ["tail", "-f", "/dev/null"]
