activity-metadata-section:
  stop_materials_tags:
    - ActivityMetadataSectionTag
    - ActivityMetadataTypeTag
  stop_tags:
    - ActivityMetadataSectionTag
activity-metadata-type:
  priority_descriptions:
    - 'This is a Priority 1 activity that should not be skipped. It is tightly connected to the lesson objective.'
    - 'This is a Priority 2 activity that can be skipped if running short on time. It is less tightly connected to the lesson objective. It might be designed as an extension or to ensure maintenance of prior skills.'
    - 'This is a Priority 3 activity that can be skipped if running short on time. It is not connected to the lesson objective. It might be designed in anticipation of upcoming learning.'
  stop_tags:
    - ActivityMetadataSectionTag
    - ActivityMetadataTypeTag
assess:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
latex:
  # RGB representation of the `math-base` color
  color: '0,166,153'
et:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
key:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
materials:
  stop_tags:
    - ActivityMetadataSectionTag
    - ActivityMetadataTypeTag
pdf_templates_path:
rubric:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
section:
  priority_descriptions:
    - 'This is a Priority 1 activity that should not be skipped. It is tightly connected to the focus objective(s) of the lesson or unit.'
    - 'This is a Priority 2 activity that can be moved or adapted if running short on time. It is less tightly connected to the focus objective(s) of the lesson or unit.'
  stop_tags:
    - SectionTag
sh:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
templates_paths:
th:
  stop_tags:
    - AssessTag
    - EtTag
    - KeyTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
